[project]
name = "antislop-vllm"
version = "0.1.0"
description = "OpenAI text-completions compatible anti-slop vLLM proxy"
readme = "README.md"
authors = [
    { name = "Sam Paech" }
]
requires-python = ">=3.11"
dependencies = [
    "datasets>=4.4.1",
    "fastapi>=0.121.1",
    "nltk>=3.6.0",
    "openai>=1.0.0",
    "pandas>=2.3.3",
    "pyyaml>=6.0",
    "regex>=2025.11.3",
    "tiktoken>=0.4.0",
    "tqdm>=4.67.1",
    "transformers>=4.40.0",
    "uvicorn[standard]>=0.38.0",
    "wordfreq>=3.1.1",
]

[project.scripts]
antislop-vllm = "antislop_vllm:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
